name: eztags
description: Simple pure-dart package to write ID3 tags to any type of file
version: 1.0.1
homepage: https://github.com/jaq-the-cat/eztags

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http: ^0.13.4}
